[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"
  base = "/"

[[redirects]]
from = "/*"
to = "index.html"
status = 200

[dev]
  command = "npm run dev"

[functions]
  node_bundler = "esbuild"